// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRequirements() {
  return window['go']['app']['App']['GetRequirements']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function IsWindowVisible() {
  return window['go']['app']['App']['IsWindowVisible']();
}

export function Login(arg1, arg2) {
  return window['go']['app']['App']['Login'](arg1, arg2);
}

export function MinimizeToTray() {
  return window['go']['app']['App']['MinimizeToTray']();
}

export function OnWindowClose() {
  return window['go']['app']['App']['OnWindowClose']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['app']['App']['ToggleWindow']();
}
