// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAccessibilityPermission() {
  return window['go']['app']['App']['CheckAccessibilityPermission']();
}

export function CheckScreenPermission() {
  return window['go']['app']['App']['CheckScreenPermission']();
}

export function GetAudioDevices() {
  return window['go']['app']['App']['GetAudioDevices']();
}

export function GetAudioSettings() {
  return window['go']['app']['App']['GetAudioSettings']();
}

export function GetCaptureDevices() {
  return window['go']['app']['App']['GetCaptureDevices']();
}

export function GetRecordingStatus() {
  return window['go']['app']['App']['GetRecordingStatus']();
}

export function GetRequirements() {
  return window['go']['app']['App']['GetRequirements']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function IsWindowVisible() {
  return window['go']['app']['App']['IsWindowVisible']();
}

export function Login(arg1, arg2) {
  return window['go']['app']['App']['Login'](arg1, arg2);
}

export function MinimizeToTray() {
  return window['go']['app']['App']['MinimizeToTray']();
}

export function OnWindowClose() {
  return window['go']['app']['App']['OnWindowClose']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function RequestAccessibilityPermission() {
  return window['go']['app']['App']['RequestAccessibilityPermission']();
}

export function RequestScreenPermission() {
  return window['go']['app']['App']['RequestScreenPermission']();
}

export function SaveAudioSettings(arg1) {
  return window['go']['app']['App']['SaveAudioSettings'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function StartRecording() {
  return window['go']['app']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['app']['App']['StopRecording']();
}

export function ToggleWindow() {
  return window['go']['app']['App']['ToggleWindow']();
}
