// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRequirements() {
  return window['go']['app']['App']['GetRequirements']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['app']['App']['Login'](arg1, arg2);
}

export function OnWindowClose() {
  return window['go']['app']['App']['OnWindowClose']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}
